apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    service: order-service
    version: order
spec:
  type: ClusterIP
  selector:
    app: order-service
    service: order-service
    version: order
  ports:
    - protocol: TCP
      port: 80
      name: tcp
      targetPort: 9002
